info:
  version: 1.0.0
  description: "Freecli - gNB module"

configuration:
  amfInterface:
    ipv4Addr: "172.16.10.2"
    port: 38412
  upfInterface:
    ipv4Addr: "172.16.10.2"
    port: 2152
  ngranInterface:
    ipv4Addr: "172.16.10.3"
    port: 9487
  gtpInterface:
    ipv4Addr: "172.16.10.3"
    port: 2152
  ueSubnet: "60.60.0.0"
  security:
    networkName: 5G:mnc093.mcc208.3gppnetwork.org
    k: 5122250214c33e723a5dd523fc145fc0
    opc: 981d464c7c52eb6e5036234984ad0bcf
    op: c9e8763286b5b9ffbdf56e1297d0887b
    sqn: 16f3b3f70fc2
  snssai:
    - sst: 1
      sd: "112233"
    - sst: 1
      sd: "010203"
  dnn:
    - internet
    - voip
  ue:
    - supi: imsi-2089300007487
      plmn: 20893
    - supi: imsi-2089300007486
      plmn: 20893
